export const NOTIFICATION_TIMING = {
  AT_START_TIME: 'AT_START_TIME',
  FIVE_MINUTES_BEFORE: 'FIVE_MINUTES_BEFORE',
  TEN_MINUTES_BEFORE: 'TEN_MINUTES_BEFORE',
  FIFTEEN_MINUTES_BEFORE: 'FIFTEEN_MINUTES_BEFORE',
  THIRTY_MINUTES_BEFORE: 'THIRTY_MINUTES_BEFORE',
  ONE_HOUR_BEFORE: 'ONE_HOUR_BEFORE',
  ONE_DAY_BEFORE: 'ONE_DAY_BEFORE',
  TWO_DAYS_BEFORE: 'TWO_DAYS_BEFORE',
  THREE_DAYS_BEFORE: 'THREE_DAYS_BEFORE',
  ONE_WEEK_BEFORE: 'ONE_WEEK_BEFORE',
  NONE: 'NONE',
} as const;

export const NOTIFICATION_LABELS = {
  [NOTIFICATION_TIMING.NONE]: '알림 안함',
  [NOTIFICATION_TIMING.AT_START_TIME]: '이벤트 시간',
  [NOTIFICATION_TIMING.FIVE_MINUTES_BEFORE]: '5분 전',
  [NOTIFICATION_TIMING.TEN_MINUTES_BEFORE]: '10분 전',
  [NOTIFICATION_TIMING.FIFTEEN_MINUTES_BEFORE]: '15분 전',
  [NOTIFICATION_TIMING.THIRTY_MINUTES_BEFORE]: '30분 전',
  [NOTIFICATION_TIMING.ONE_HOUR_BEFORE]: '1시간 전',
  [NOTIFICATION_TIMING.ONE_DAY_BEFORE]: '1일 전',
  [NOTIFICATION_TIMING.TWO_DAYS_BEFORE]: '2일 전',
  [NOTIFICATION_TIMING.THREE_DAYS_BEFORE]: '3일 전',
  [NOTIFICATION_TIMING.ONE_WEEK_BEFORE]: '7일 전',
} as const;

export const NOTIFICATION_OPTIONS = [
  NOTIFICATION_TIMING.NONE,
  NOTIFICATION_TIMING.AT_START_TIME,
  NOTIFICATION_TIMING.FIVE_MINUTES_BEFORE,
  NOTIFICATION_TIMING.TEN_MINUTES_BEFORE,
  NOTIFICATION_TIMING.FIFTEEN_MINUTES_BEFORE,
  NOTIFICATION_TIMING.THIRTY_MINUTES_BEFORE,
  NOTIFICATION_TIMING.ONE_HOUR_BEFORE,
  NOTIFICATION_TIMING.ONE_DAY_BEFORE,
  NOTIFICATION_TIMING.TWO_DAYS_BEFORE,
].map((value) => ({ value, label: NOTIFICATION_LABELS[value] }));

export const ALL_DAY_NOTIFICATION_OPTIONS = [
  { value: NOTIFICATION_TIMING.NONE, label: NOTIFICATION_LABELS[NOTIFICATION_TIMING.NONE] },
  { value: NOTIFICATION_TIMING.ONE_DAY_BEFORE, label: '1일 전(오전 9시)' },
  { value: NOTIFICATION_TIMING.TWO_DAYS_BEFORE, label: '2일 전(오전 9시)' },
  { value: NOTIFICATION_TIMING.THREE_DAYS_BEFORE, label: '3일 전(오전 9시)' },
  { value: NOTIFICATION_TIMING.ONE_WEEK_BEFORE, label: '7일 전(오전 9시)' },
];
