export const NOTIFICATION_TIMING = {
  AT_START_TIME: 'AT_START_TIME',
  FIVE_MINUTES_BEFORE: 'FIVE_MINUTES_BEFORE',
  TEN_MINUTES_BEFORE: 'TEN_MINUTES_BEFORE',
  FIFTEEN_MINUTES_BEFORE: 'FIFTEEN_MINUTES_BEFORE',
  THIRTY_MINUTES_BEFORE: 'THIRTY_MINUTES_BEFORE',
  ONE_HOUR_BEFORE: 'ONE_HOUR_BEFORE',
  ONE_DAY_BEFORE: 'ONE_DAY_BEFORE',
  TWO_DAYS_BEFORE: 'TWO_DAYS_BEFORE',
  THREE_DAYS_BEFORE: 'THREE_DAYS_BEFORE',
  ONE_WEEK_BEFORE: 'ONE_WEEK_BEFORE',
  NONE: 'NONE',
} as const;

export const NOTIFICATION_OPTIONS = [
  { value: NOTIFICATION_TIMING.NONE, label: '알림 안함' },
  { value: NOTIFICATION_TIMING.AT_START_TIME, label: '이벤트 시간' },
  { value: NOTIFICATION_TIMING.FIVE_MINUTES_BEFORE, label: '5분 전' },
  { value: NOTIFICATION_TIMING.TEN_MINUTES_BEFORE, label: '10분 전' },
  { value: NOTIFICATION_TIMING.FIFTEEN_MINUTES_BEFORE, label: '15분 전' },
  { value: NOTIFICATION_TIMING.THIRTY_MINUTES_BEFORE, label: '30분 전' },
  { value: NOTIFICATION_TIMING.ONE_HOUR_BEFORE, label: '1시간 전' },
  { value: NOTIFICATION_TIMING.ONE_DAY_BEFORE, label: '1일 전' },
  { value: NOTIFICATION_TIMING.TWO_DAYS_BEFORE, label: '2일 전' },
];

export const ALL_DAY_NOTIFICATION_OPTIONS = [
  { value: NOTIFICATION_TIMING.NONE, label: '알림 안함' },
  { value: NOTIFICATION_TIMING.ONE_DAY_BEFORE, label: '1일 전(오전 9시)' },
  { value: NOTIFICATION_TIMING.TWO_DAYS_BEFORE, label: '2일 전(오전 9시)' },
  { value: NOTIFICATION_TIMING.THREE_DAYS_BEFORE, label: '3일 전(오전 9시)' },
  { value: NOTIFICATION_TIMING.ONE_WEEK_BEFORE, label: '7일 전(오전 9시)' },
];
